/**
 * @file    ai_denoise_model.cpp
 * @brief   Embedded FDnCNN model data accessors
 * @license MIT
 *
 * @details
 * Exposes the param/bin byte arrays embedded in assets/model_core.{id.h,mem.h}
 * to the NcnnDenoiser. The headers are generated by ncnn2mem and contain the
 * model as `static const unsigned char` arrays with long mangled symbol names.
 *
 * Ported from allenk/GeminiWatermarkTool ai_denoise_model.cpp (MIT);
 * FDnCNN model (c) cszn/KAIR (MIT).
 */

#ifdef WMR_AI_DENOISE

#include "model_core.id.h"
#include "model_core.mem.h"

namespace wmr::ai_model {

const unsigned char* param_data() {
    return S__CodeForge_tools_gemini_watermark_tool_release_repo_external_ncnn_model_convert_output_model_core_fp16_param_bin;
}

const unsigned char* bin_data() {
    return S__CodeForge_tools_gemini_watermark_tool_release_repo_external_ncnn_model_convert_output_model_core_fp16_bin;
}

} // namespace wmr::ai_model

#endif // WMR_AI_DENOISE
